# Generated by Django 6.0 on 2025-12-30 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spontaneous', models.BooleanField(default=False, verbose_name='Candidature spontanée')),
                ('civility', models.CharField(choices=[('monsieur', 'Monsieur'), ('madame', 'Madame'), ('mademoiselle', 'Mademoiselle')], max_length=20, verbose_name='Civilité')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('address', models.TextField(verbose_name='Adresse complète')),
                ('contract_type_sought', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('alternance', 'Alternance'), ('interim', 'Intérim'), ('freelance', 'Freelance'), ('temps_partiel', 'Temps partiel')], max_length=20, verbose_name='Type de contrat recherché')),
                ('experience', models.JSONField(default=list, help_text='Liste des expériences professionnelles', verbose_name='Expérience')),
                ('education_level', models.CharField(max_length=255, verbose_name="Niveau d'études")),
                ('current_salary', models.BigIntegerField(blank=True, null=True, verbose_name='Salaire actuel (facultatif)')),
                ('expected_salary', models.BigIntegerField(verbose_name='Prétention salariale')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examinée'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
